apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: oceanbase

patches:
- target:
    kind: StatefulSet
    name: oceanbase
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 3
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: 16Gi
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: 32Gi

commonLabels:
  environment: prod 