global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # OBAgent metrics scraping configuration
  - job_name: 'obagent'
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names: ['oceanbase']
        selectors:
          - role: pod
            label: 'ref-obcluster=obcluster'
    relabel_configs:
      # Keep only pods with ref-obcluster=obcluster label
      - source_labels: [__meta_kubernetes_pod_label_ref_obcluster]
        regex: obcluster
        action: keep
      # Add pod name as instance label
      - source_labels: [__meta_kubernetes_pod_name]
        target_label: instance
      # Add node name as node label
      - source_labels: [__meta_kubernetes_pod_node_name]
        target_label: node
    metrics_path: '/metrics/node'
    scheme: http
    params:
      # OBAgent metrics modules to collect
      module: ['ob_basic', 'os_basic', 'ob_ext']
    static_configs:
      - targets: ['localhost:8088']  # Default OBAgent metrics port

  - job_name: 'oceanbase'
    static_configs:
      - targets: ['oceanbase:22883']
    metrics_path: '/metrics'
    
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:8001']
    metrics_path: '/metrics' 