global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'oceanbase'
    static_configs:
      - targets: ['oceanbase:2881']
    metrics_path: '/metrics'
    
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/metrics' 