version: '3.8'

services:
  neo4j:
    image: neo4j:4.4
    container_name: distdiag_neo4j
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/distdiag
      - NEO4J_dbms_memory_heap_max__size=4G
    volumes:
      - neo4j_data:/data
      - ./config/neo4j:/conf

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: distdiag_backend
    ports:
      - "18000:8001"
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=distdiag
      - MODEL_PATH=/app/models
    volumes:
      - ../backend:/app
      - ../models:/app/models
    depends_on:
      - neo4j

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: distdiag_frontend
    ports:
      - "13000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:18000
    volumes:
      - ../frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  prometheus:
    image: prom/prometheus:latest
    container_name: distdiag_prometheus
    ports:
      - "19090:9090"
    volumes:
      - ./config/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    depends_on:
      - backend

  oceanbase:
    image: oceanbase/oceanbase-ce:4.3.0
    container_name: distdiag_oceanbase
    ports:
      - "2881:2881"  # SQL port
      - "2882:2882"  # RPC port
    environment:
      - OB_ROOT_PASSWORD=password123
    volumes:
      - oceanbase_data:/root/oceanbase

volumes:
  neo4j_data:
  prometheus_data:
  oceanbase_data: 