version: '3.8'

services:
  neo4j:
    image: neo4j:4.4
    container_name: distdiag_neo4j
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/distdiag
      - NEO4J_dbms_memory_heap_max__size=4G
    volumes:
      - neo4j_data:/data
      - ./config/neo4j:/conf

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: distdiag_backend
    ports:
      - "8000:8000"
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=distdiag
      - MODEL_PATH=/app/models
    volumes:
      - ../backend:/app
      - ../models:/app/models
    depends_on:
      - neo4j

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: distdiag_frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    volumes:
      - ../frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  neo4j_data: 