apiVersion: oceanbase.oceanbase.com/v1
kind: OBCluster
metadata:
  name: obcluster
  namespace: oceanbase
spec:
  clusterName: obcluster
  mode: service
  topology:
    - zone: zone1
      replica: 1
    - zone: zone2
      replica: 1
    - zone: zone3
      replica: 1
  observer:
    resource:
      cpu: 4
      memory: 8Gi
    storage:
      dataStorage:
        size: 50Gi
      redoLogStorage:
        size: 50Gi
      logStorage:
        size: 20Gi
  parameters:
    - name: system_memory
      value: 4G
    - name: memory_limit
      value: 24G
  obproxy:
    replicas: 1
    resource:
      cpu: 2
      memory: 4Gi
    parameters:
      - name: proxy_mem_limited
        value: "4G"
      - name: enable_compression_protocol
        value: "True" 