apiVersion: oceanbase.oceanbase.com/v1alpha1
kind: OBCluster
metadata:
  name: obcluster
  namespace: oceanbase
spec:
  clusterName: obcluster
  clusterId: 1
  userSecrets:
    root: root-password
    proxyro: proxyro-password
  topology:
    - zone: zone1
      replica: 1
      nodeSelector:
        zone: zone1
    - zone: zone2
      replica: 1
      nodeSelector:
        zone: zone2
    - zone: zone3
      replica: 1
      nodeSelector:
        zone: zone3
  parameters:
    - name: "init_memory_limit"
      value: "8G"
    - name: "system_memory"
      value: "2G"
    - name: "memory_limit"
      value: "8G"
    - name: "cpu_count"
      value: "2"
  observer:
    image: oceanbase/oceanbase-cloud-native:4.2.5.1-101000092024120918
    command:
    - /home/admin/oceanbase/bin/observer
    - --nodaemon
    - --appname
    - obcluster
    - --cluster_id
    - "1"
    - --zone
    - zone1
    - -i
    - eth0
    - -p
    - "2881"
    - -P
    - "2882"
    - -d
    - /home/admin/oceanbase/store
    - -l
    - info
    - -o
    - config_additional_dir=/home/admin/oceanbase/store/etc,cpu_count=16,datafile_size=6G,log_disk_size=28G,enable_syslog_recycle=true,max_syslog_file_count=4,datafile_maxsize=28G,datafile_next=3G,init_memory_limit=8G,system_memory=2G,memory_limit=8G
    resource:
      cpu: 2
      memory: 10Gi
    storage:
      dataStorage:
        storageClass: local-path
        size: 30Gi
      redoLogStorage:
        storageClass: local-path
        size: 30Gi
      logStorage:
        storageClass: local-path
        size: 20Gi
  monitor:
    image: oceanbase/obagent:4.2.2-100000042024011120
    resource:
      cpu: 1
      memory: 1Gi 
      
# observer boot command
# /home/admin/oceanbase/bin/observer --nodaemon --appname obcluster --cluster_id 1 --zone zone1 -i eth0 -p 2881 -P 2882 -d /home/admin/oceanbase/store -l info -o config_additional_dir=/home/admin/oceanbase/store/etc,cpu_count=16,datafile_size=6G,log_disk_size=28G,enable_syslog_recycle=true,max_syslog_file_count=4,datafile_maxsize=28G,datafile_next=3G,init_memory_limit=8G,system_memory=2G,memory_limit=8G