apiVersion: v1
kind: Secret
metadata:
  name: root-password
  namespace: oceanbase
type: Opaque
data:
  password: cGFzc3dvcmQxMjM=  # base64 encoded "password123"
---
apiVersion: v1
kind: Secret
metadata:
  name: proxyro-password
  namespace: oceanbase
type: Opaque
data:
  password: cHJveHlybzEyMw==  # base64 encoded "proxyro123" 