apiVersion: batch/v1
kind: Job
metadata:
  name: tsar-installer
  namespace: oceanbase
spec:
  template:
    spec:
      serviceAccountName: tsar-admin
      containers:
      - name: installer
        image: bitnami/kubectl:latest
        command:
        - /bin/sh
        - -c
        - |
          # Get all OceanBase pods
          for pod in $(kubectl get pods -n oceanbase -l app=ob -o name); do
            echo "Installing tsar in pod ${pod}..."
            # Install build dependencies and tsar in each pod
            kubectl exec -n oceanbase ${pod} -c observer -- sh -c '
              apt-get update && \
              apt-get install -y git build-essential libpcre3-dev && \
              cd /tmp && \
              rm -rf tsar && \
              git clone https://github.com/alibaba/tsar.git && \
              cd tsar && \
              make && \
              make install && \
              chmod -R 755 /usr/local/bin/tsar /usr/local/tsar /etc/tsar
            '
          done
      restartPolicy: Never
  backoffLimit: 4
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tsar-admin
  namespace: oceanbase
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tsar-admin
rules:
- apiGroups: [""]
  resources: ["pods", "pods/exec"]
  verbs: ["get", "list", "watch", "create"]
- apiGroups: [""]
  resources: ["pods/exec", "pods/portforward"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tsar-admin
subjects:
- kind: ServiceAccount
  name: tsar-admin
  namespace: oceanbase
roleRef:
  kind: ClusterRole
  name: tsar-admin
  apiGroup: rbac.authorization.k8s.io 