apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: oceanbase

patches:
- target:
    kind: StatefulSet
    name: oceanbase
  patch: |-
    - op: replace
      path: /spec/replicas
      value:3
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: 2Gi
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: 4Gi
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/cpu
      value: "1"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/cpu
      value: "2"
    - op: replace
      path: /spec/volumeClaimTemplates/0/spec/resources/requests/storage
      value: 20Gi
- target:
    kind: Service
    name: oceanbase
  patch: |-
    - op: replace
      path: /spec/type
      value: NodePort

commonLabels:
  environment: dev